print(" ================================== ")
print("|         STUDENT BIO CARD         |")
print("|==================================|")
print("| Name    : Namratha V             |")
print("| Age     : 22                     |")
print("| Course  : Gen AI                 |")
print("| College : SJBIT                  |")
print("| Email   :namratha@gmail.com      |")
print(" ================================== ")